"""Zip export of one recording, for the operator's own archive or analysis.

The zip holds exactly four entries and nothing else from the data directory:

* ``manifest.json``: recording metadata, a consent *summary* (no free text
  beyond the stated purpose), schema/parser/format versions, file hashes and a
  provenance statement.
* ``frames.jsonl.gz``: the recording file, byte for byte.
* ``events.csv``: operator label events and the link events stored in the file.
* ``PROVENANCE.txt``: the provenance statement in plain words.

Only one export per recording is kept (older ones are replaced), so exports
never grow beyond the size of the recordings themselves.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import os
import time
import zipfile
from pathlib import Path
from typing import Any

from .. import PARSER_VERSION, SCHEMA_VERSION, __version__
from ..recording_format import RECORDING_FORMAT, RecordingFormatError, read_header
from ..schemas import SOURCE_MODE_BANNER, SourceMode
from .db import Database
from .models import RecordingInfo, RecordingStatus, validate_id
from .recordings import EXPORTS_SUBDIR, iter_recording_events, recording_file_for_read

__all__ = ["EXPORT_FORMAT", "ExportError", "export_recording", "provenance_statement"]

EXPORT_FORMAT = "roomsense-export-v1"
_MAX_LINK_EVENTS = 100_000  # bound memory for events.csv
_CSV_COLUMNS = ("source", "t_unix_ns", "kind", "label", "link_id", "receiver_id", "detail", "notes", "event_id")


class ExportError(RuntimeError):
    """The recording cannot be exported (missing, still recording, unreadable)."""


def provenance_statement(info: RecordingInfo) -> str:
    """Plain-language statement of what the exported data is and is not."""
    mode = info.source_mode.value
    original = "UNKNOWN" if info.original_source_mode is None else info.original_source_mode.value
    lines = [
        f"RoomSense recording {info.recording_id}",
        f"Source mode while recording: {mode} ({SOURCE_MODE_BANNER[info.source_mode]})",
        f"Original source mode of the data: {original}",
    ]
    if info.synthetic:
        lines += [
            "",
            "SIMULATION / SYNTHETIC DATA. These values were generated by software. They are not",
            "measurements of any room and can never be used as validation evidence.",
        ]
    elif info.source_mode == SourceMode.REPLAY:
        lines += [
            "",
            "This recording captured a REPLAY of an earlier recording. It is not an independent",
            "live observation and does not count as validation evidence.",
        ]
    else:
        lines += [
            "",
            "These are raw CSI values as reported by the operator's ESP32 receiver(s). Metadata that",
            "the firmware or chip did not report is stored as null (unavailable), not estimated.",
        ]
    lines += [
        "",
        "Nothing in this export is validated sensing. Motion, zone or pose interpretations of",
        "this data are validated only where the RoomSense through-wall validation report says",
        "VALIDATED for the same setup, criteria version and source mode.",
        f"Recording status: {info.status.value}"
        + (f" ({info.stop_reason})" if info.stop_reason else ""),
        f"Schema version {SCHEMA_VERSION}; parser {PARSER_VERSION}; format {RECORDING_FORMAT}.",
    ]
    return "\n".join(lines) + "\n"


def _csv_safe(value: Any) -> str:
    """Neutralise spreadsheet formula injection in free-text cells."""
    if value is None:
        return ""
    text = str(value)
    if text and text[0] in ("=", "+", "-", "@", "\t", "\r"):
        return "'" + text
    return text


def _events_csv(db: Database, info: RecordingInfo, frames_path: Path) -> tuple[str, int, int, bool]:
    labels = {e.event_id: e for e in db.list_events(recording_id=info.recording_id, limit=None)}
    # Label events entered during the recording without an explicit link to it
    # still describe it, so include the session's events within its time span.
    end = info.ended_at_unix_ns
    if end is not None:
        for e in db.list_events(session_id=info.session_id, start_unix_ns=info.created_at_unix_ns,
                                end_unix_ns=end, limit=None):
            if e.recording_id in (None, info.recording_id):
                labels.setdefault(e.event_id, e)
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(_CSV_COLUMNS)
    for e in sorted(labels.values(), key=lambda e: (e.t_unix_ns, e.event_id)):
        w.writerow(["label", e.t_unix_ns, e.kind.value, _csv_safe(e.label), "", "", "", _csv_safe(e.notes), e.event_id])
    n_link = 0
    truncated = False
    for ev in iter_recording_events(frames_path):
        if n_link >= _MAX_LINK_EVENTS:
            truncated = True
            break
        w.writerow([
            "link", ev.get("host_unix_ns") if isinstance(ev.get("host_unix_ns"), int) else "",
            _csv_safe(ev.get("kind")), "", _csv_safe(ev.get("link_id")), _csv_safe(ev.get("receiver_id")),
            _csv_safe(ev.get("detail")), "", "",
        ])
        n_link += 1
    return buf.getvalue(), len(labels), n_link, truncated


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def export_recording(db: Database, data_dir: Path, recording_id: str, *, now_ns: int | None = None) -> Path:
    """Write ``<data_dir>/exports/<recording_id>.export.<UTC stamp>.zip`` and
    return its path. Raises ``ValueError`` for an unsafe ID and
    :class:`ExportError` if the recording cannot be exported."""
    validate_id(recording_id, "recording_id")
    info = db.get_recording(recording_id)
    if info is None:
        raise ExportError(f"recording {recording_id} not found")
    if info.status == RecordingStatus.RECORDING:
        raise ExportError("stop the recording before exporting it")
    try:
        frames_path = recording_file_for_read(data_dir, recording_id)
        header = read_header(frames_path)
    except FileNotFoundError as exc:
        raise ExportError(str(exc)) from exc
    except (RecordingFormatError, OSError, ValueError) as exc:
        raise ExportError(f"recording file unreadable: {exc}") from exc

    consent = db.get_consent(info.consent_id)
    events_csv, n_labels, n_link, link_truncated = _events_csv(db, info, frames_path)
    provenance = provenance_statement(info)
    now = time.time_ns() if now_ns is None else int(now_ns)

    manifest: dict[str, Any] = {
        "export_format": EXPORT_FORMAT,
        "exported_at_unix_ns": now,
        "app_version": __version__,
        "schema_version": SCHEMA_VERSION,
        "parser_version": PARSER_VERSION,
        "recording_format": RECORDING_FORMAT,
        "file_header": {
            "format": header.get("format"),
            "schema_version": header.get("schema_version"),
            "parser_version": header.get("parser_version"),
            "config_version": header.get("config_version"),
        },
        "recording": info.model_dump(mode="json"),
        "consent": None if consent is None else consent.summary(),
        "consent_record_missing": consent is None,
        "provenance": {
            "source_mode": info.source_mode.value,
            "original_source_mode": None if info.original_source_mode is None else info.original_source_mode.value,
            "synthetic": info.synthetic,
            "banner": "SIMULATION / SYNTHETIC DATA" if info.synthetic else SOURCE_MODE_BANNER[info.source_mode],
            "statement": provenance,
        },
        "validation_evidence": {
            "usable_as_validation_evidence": info.usable_as_validation_evidence,
            "validated_sensing": False,
            "note": "This export makes no sensing claim. See the through-wall validation report.",
        },
        "counts": {"label_events": n_labels, "link_events": n_link, "link_events_truncated": link_truncated},
        "files": {
            "frames.jsonl.gz": {"bytes": frames_path.stat().st_size, "sha256": _sha256_file(frames_path)},
            "events.csv": {"sha256": hashlib.sha256(events_csv.encode("utf-8")).hexdigest()},
            "PROVENANCE.txt": {"sha256": hashlib.sha256(provenance.encode("utf-8")).hexdigest()},
        },
    }

    exports = (Path(data_dir) / EXPORTS_SUBDIR).resolve()
    exports.mkdir(parents=True, exist_ok=True)
    # Nanoseconds in the name keep two exports within one second distinct.
    stamp = time.strftime("%Y%m%dT%H%M%S", time.gmtime(now // 1_000_000_000)) + f"{now % 1_000_000_000:09d}Z"
    final = exports / f"{recording_id}.export.{stamp}.zip"
    tmp = exports / f".{recording_id}.export.{stamp}.zip.partial"
    try:
        with zipfile.ZipFile(tmp, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("manifest.json", json.dumps(manifest, indent=2, sort_keys=True, allow_nan=False))
            # Already gzip-compressed; deflating it again only costs time.
            zf.write(frames_path, arcname="frames.jsonl.gz", compress_type=zipfile.ZIP_STORED)
            zf.writestr("events.csv", events_csv)
            zf.writestr("PROVENANCE.txt", provenance)
        os.replace(tmp, final)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise
    for old in exports.glob(f"{recording_id}.export.*.zip"):
        if old != final and old.parent == exports:
            old.unlink(missing_ok=True)
    return final
