/**
 * Permanent header shown on every page. It is the single place that says
 * where the data comes from, how old it is and what the system can and
 * cannot claim. All values come from the backend status; ages are computed
 * client-side so they keep growing if updates stop.
 */

import type { ActivityResult, LinkStatus, SystemStatus } from '../api/types';
import type { LiveSnapshot } from '../api/ws';
import {
  CAPABILITY_LETTER,
  SIMULATED_BANNER_TEXT,
  calibrationInfo,
  enabledCapabilities,
  sourceBanner,
  throughWallInfo,
  unsupportedCapabilities,
} from '../lib/banner';
import { formatAge, isStale, linkAges, newestMeasurementAgeS } from '../lib/freshness';
import { fmtNum } from '../lib/format';
import { qualityCss } from '../lib/linkStyle';
import { CapabilityChips } from './CapabilityChips';

export function SimulatedBanner() {
  return (
    <div className="sim-banner" role="alert" aria-live="assertive">
      <span className="sim-banner__text">{SIMULATED_BANNER_TEXT}</span>
      <span className="sim-banner__sub">Generated by the built-in simulator. Nothing on screen was measured by a sensor.</span>
    </div>
  );
}

function NoConnectionBanner({ live, now }: { live: LiveSnapshot; now: number }) {
  const retryIn = live.nextRetryAtMs !== null ? Math.max(0, (live.nextRetryAtMs - now) / 1000) : null;
  return (
    <div className="offline-banner" role="alert">
      <span className="offline-banner__text">NO CONNECTION TO BACKEND</span>
      <span className="offline-banner__sub">
        {live.connection === 'connecting'
          ? 'Connecting to /api/ws …'
          : live.connection === 'open'
            ? 'Socket open; waiting for the first status message …'
            : retryIn !== null
            ? `Retrying in ${retryIn.toFixed(0)} s (attempt ${live.attempt}).`
            : 'Waiting to reconnect.'}{' '}
        No data is shown until the backend answers. {live.lastError ? `Last error: ${live.lastError}` : ''}
      </span>
    </div>
  );
}

function LinkRate({
  link,
  activity,
  ageS,
  timeoutS,
}: {
  link: LinkStatus | undefined;
  activity: ActivityResult | undefined;
  ageS: number | null;
  timeoutS: number;
}) {
  const level = activity?.quality.level ?? null;
  const stale = isStale(ageS, timeoutS);
  return (
    <span className={`link-rate ${stale ? 'link-rate--stale' : ''}`}>
      <span className="link-rate__rate" title="Measured acquisition rate over the last few seconds (not the configured rate)">
        {fmtNum(link?.acquisition_rate_hz ?? null, 1, 'Hz')}
      </span>
      <span className="link-rate__quality" style={{ color: qualityCss(level) }} title="Data quality level of the latest window">
        quality {level ?? 'unavailable'}
      </span>
      {stale && <span className="link-rate__stale">stale</span>}
    </span>
  );
}

function Details({ status, receivedAt, now }: { status: SystemStatus; receivedAt: number; now: number }) {
  const cal = calibrationInfo(status);
  const tw = throughWallInfo(status);
  const ages = linkAges(status, receivedAt, now);
  const enabled = enabledCapabilities(status.capabilities);
  const unsupported = unsupportedCapabilities(status.capabilities);
  return (
    <div className="status-details">
      <div className="status-details__group">
        <span className="status-details__label">Links (measured rate · quality)</span>
        {ages.size === 0 ? (
          <span className="muted">No links reported by the backend.</span>
        ) : (
          <ul className="link-rates">
            {[...ages.entries()].map(([id, age]) => (
              <li key={id}>
                <code>{id}</code>{' '}
                <LinkRate
                  link={status.links.find((l) => l.link_id === id)}
                  activity={status.activity.find((a) => a.link_id === id)}
                  ageS={age}
                  timeoutS={status.stale_clear_timeout_s}
                />
              </li>
            ))}
          </ul>
        )}
      </div>
      <div className="status-details__group">
        <span className={`pill ${cal.valid ? 'pill--ok' : 'pill--warn'}`}>{cal.label}</span>
        <span className="status-details__text">{cal.detail}</span>
      </div>
      <div className="status-details__group">
        <span className="pill pill--neutral">Localization</span>
        <span className="status-details__text">{status.localization_status}</span>
      </div>
      <div className="status-details__group">
        <span className={`pill pill--${tw.severity}`}>{tw.label}</span>
        {tw.detail && <span className="status-details__text">{tw.detail}</span>}
      </div>
      <div className="status-details__group">
        <span className="pill pill--neutral">Capabilities</span>
        <span className="status-details__text">
          Enabled now: {enabled.length > 0 ? enabled.map((c) => CAPABILITY_LETTER[c]).join(', ') : 'none'} · Unsupported:{' '}
          {unsupported.length > 0 ? unsupported.map((c) => CAPABILITY_LETTER[c]).join(', ') : 'none'}
        </span>
      </div>
      {(status.unsupported_capabilities ?? []).length > 0 && (
        <div className="status-details__group status-details__group--scope">
          <span className="pill pill--neutral">Not supported</span>
          <span className="status-details__text">
            {(status.unsupported_capabilities ?? []).map((u, i) => (
              <span key={u.id} title={u.reason}>
                {i > 0 && ' · '}
                {u.claim}
              </span>
            ))}
          </span>
        </div>
      )}
      <div className="status-details__group status-details__group--scope">
        <span className="pill pill--neutral">Operating scope</span>
        <span className="status-details__text">{status.operating_scope}</span>
      </div>
    </div>
  );
}

export function StatusHeader({ live, now, onOpenCapabilities }: { live: LiveSnapshot; now: number; onOpenCapabilities: () => void }) {
  const connected = live.connection === 'open' && live.status !== null && live.statusReceivedAtMs !== null;
  const status = connected ? live.status : null;
  const receivedAt = live.statusReceivedAtMs ?? now;
  const banner = sourceBanner(status, connected);
  const newestAge = status ? newestMeasurementAgeS(status, receivedAt, now) : null;
  const ageStale = status ? isStale(newestAge, status.stale_clear_timeout_s) : true;

  return (
    <>
      {/* Sticky: source/simulation/connection state must stay visible while scrolling. */}
      <div className="header-sticky">
        {banner.showSimulatedBanner && <SimulatedBanner />}
        {!connected && <NoConnectionBanner live={live} now={now} />}
        <header className="status-header">
          <div className="status-header__row">
            <div className="brand">
              <span className="brand__name">WiFi RoomSense 3D</span>
              <span className="brand__tag">local · experimental</span>
            </div>
            <div className={`source-pill source-pill--${banner.severity}`} aria-label="Data source">
              <span className="source-pill__text">{banner.text}</span>
              {status && <span className="source-pill__state">{status.source_state.replace(/_/g, ' ')}</span>}
            </div>
            {status?.hardware_required && (
              <span className="badge badge--hw" title="Real ESP32 hardware is required for live measurements.">
                HARDWARE REQUIRED
              </span>
            )}
            {status?.recording_active && (
              <span className="badge badge--rec" title={`Recording ${status.recording_id ?? ''}`}>
                ● REC
              </span>
            )}
            <div
              className={`age ${ageStale ? 'age--stale' : ''}`}
              title="Time since the newest measured frame on any link (not the screen refresh rate)"
            >
              <span className="age__label">measurement age</span>
              <span className="age__value">{status ? formatAge(newestAge) : 'unavailable'}</span>
              {status && ageStale && <span className="age__flag">{newestAge === null ? 'no measurements' : 'stale'}</span>}
            </div>
            {status && <CapabilityChips capabilities={status.capabilities} onOpen={onOpenCapabilities} />}
          </div>
        </header>
      </div>
      {(status?.source_detail || banner.inconsistency || status) && (
        <div className="status-details-bar">
          {status?.source_detail && <div className="status-header__source-detail">Source: {status.source_detail}</div>}
          {banner.inconsistency && <div className="status-header__warning">⚠ {banner.inconsistency}</div>}
          {status && <Details status={status} receivedAt={receivedAt} now={now} />}
        </div>
      )}
    </>
  );
}
