"""SIMULATOR: synthetic CSI-shaped data. NOT a measurement of anything.

This module generates CSI-like int8 values from a deliberately simple,
physics-inspired toy model so the rest of the software (parsing-free paths,
windowing, detection state machines, UI, recording/replay) can be exercised
without hardware. Every frame it produces is labelled
``source_mode=SIMULATION``, ``input_format=synthetic-v1``, quality flag
``SYNTHETIC`` and ``device.identity_source='synthetic'`` with
``chip='synthetic'``. Results obtained on this data show that code paths
run; they say nothing about how well Wi-Fi sensing works in a real room.

The toy model (per link, per packet):

* static multipath ``H0(f) = sum_p a_p * exp(-j*2*pi*f*tau_p)`` with a
  line-of-sight path and a few reflections;
* ``MOTION``: a moving scatterer (a simulated walker in room coordinates)
  adds a path TX -> walker -> RX whose delay and amplitude change smoothly;
  its strength falls off with the walker's distance from the TX-RX segment,
  and a walker close to the line of sight also shadows it;
* ``STILL_PERSON``: a new *static* path plus a tiny slow (breathing-like)
  modulation. A variance-based motion detector is expected NOT to fire; this
  documents a known limitation, it is not a bug in the detector;
* ``DOOR``: a short, strong burst from a swinging door leaf;
* ``NEAR_SENSOR_OUTSIDE``: a walker near a point outside the target room,
  close to a sensor, strongly modulating the links near it (another known
  limitation: motion near a sensor outside the room also changes the CSI);
* ``PACKET_LOSS`` drops a fraction of packets (counter gaps);
* ``DISCONNECT`` stops a link entirely for the interval;
* plus AWGN, per-packet gain jitter, a random common phase and timing
  offset per packet (as real ESP32 CSI has), timing jitter, quantisation and
  clipping to int8.

Everything is deterministic for a given seed (numpy ``Generator`` streams
derived from the seed). The static environment uses ``environment_seed``
(default: the scenario seed) so that several sessions can share one simulated
room, e.g. for zone-estimation *software tests*.
"""

from __future__ import annotations

import dataclasses
import heapq
import logging
import math
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Iterator

import numpy as np

from .. import csi_layouts
from ..schemas import CsiFrame, DeviceIdentity, InputFormat, QualityFlag, SourceMode
from .base import CONNECTED, DISCONNECTED, EndOfStream, FrameEvent, FrameSource, LinkEvent, Sink
from .rollover import CounterUnwrapper, TimestampUnwrapper

__all__ = [
    "Episode",
    "SyntheticScenario",
    "SyntheticSource",
    "builtin_scenarios",
    "generate_frames",
    "zone_session_scenario",
    "with_seed",
    "EPISODE_KINDS",
    "SYNTHETIC_ZONES",
    "SYNTHETIC_ROOM_SIZE_M",
    "ZONES_3RX_LINKS",
    "ZONES_3RX_POSITIONS",
    "SYNTHETIC_LAYOUT",
    "SIMULATED_BANNER",
]

log = logging.getLogger(__name__)

SIMULATED_BANNER = "SIMULATED DATA - generated by a toy model, not measured"
SYNTHETIC_MODEL_VERSION = "toy-multipath-1"

EMPTY = "EMPTY"
MOTION = "MOTION"
STILL_PERSON = "STILL_PERSON"
DOOR = "DOOR"
NEAR_SENSOR_OUTSIDE = "NEAR_SENSOR_OUTSIDE"
DISCONNECT = "DISCONNECT"
PACKET_LOSS = "PACKET_LOSS"
EPISODE_KINDS = frozenset({EMPTY, MOTION, STILL_PERSON, DOOR, NEAR_SENSOR_OUTSIDE, DISCONNECT, PACKET_LOSS})

SPEED_OF_LIGHT = 299_792_458.0
DEFAULT_CARRIER_HZ = 2.437e9  # 2.4 GHz channel 6
SUBCARRIER_SPACING_HZ = 312_500.0
SYNTHETIC_CHANNEL = 6
BODY_HEIGHT_M = 1.0
# Amplitude of a person's scattered path relative to the direct path when the
# person stands on the TX-RX line (toy value, not calibrated to any room).
SCATTER_COEFF = 0.8

# Arbitrary fixed epochs so offline generation is fully deterministic.
SYNTHETIC_EPOCH_UNIX_NS = 1_700_000_000_000_000_000
SYNTHETIC_EPOCH_MONOTONIC_NS = 1_000_000_000_000

# Classic-chip LLTF, secondary channel none, LLTF only: 64 subcarriers, 128 int8.
SYNTHETIC_LAYOUT = csi_layouts.resolve_layout(
    family="classic",
    total_values=128,
    ltf_config="lltf_only",
    secondary_channel=0,
    sig_mode=None,
    cwb=None,
    stbc=None,
)
assert SYNTHETIC_LAYOUT is not None
_K_ALL = SYNTHETIC_LAYOUT.k_indices()
_VALID_POS = np.flatnonzero(SYNTHETIC_LAYOUT.valid_position_mask())
_K_VALID = _K_ALL[_VALID_POS].astype(np.float64)
_VALID_SUBCARRIERS = tuple(int(k) for k in _K_ALL[_VALID_POS])

# Simulated room (metres) shared by the builtin scenarios.
SYNTHETIC_ROOM_SIZE_M = (4.0, 3.5)
SYNTHETIC_ZONES: dict[str, tuple[float, float, float, float]] = {
    # zone id -> (x_min, x_max, y_min, y_max)
    "A": (0.0, 4.0 / 3.0, 0.0, 3.5),
    "B": (4.0 / 3.0, 8.0 / 3.0, 0.0, 3.5),
    "C": (8.0 / 3.0, 4.0, 0.0, 3.5),
}
DEMO_POSITIONS: dict[str, tuple[float, float, float]] = {
    "tx1": (0.0, 1.75, 1.0),
    "rx1": (4.0, 1.75, 1.0),
}
ZONES_3RX_POSITIONS: dict[str, tuple[float, float, float]] = {
    "tx1": (0.0, 1.75, 1.0),
    "rx1": (4.0, 0.6, 1.0),
    "rx2": (4.0, 2.9, 1.0),
    "rx3": (2.0, 3.5, 1.0),
}
ZONES_3RX_LINKS: list[tuple[str, str]] = [("tx1", "rx1"), ("tx1", "rx2"), ("tx1", "rx3")]
OUTSIDE_POINT_3RX = (4.8, 0.6)  # beyond the east wall, behind rx1
ZONES_ENVIRONMENT_SEED = 20240501


# ---------------------------------------------------------------------------
# Scenario description
# ---------------------------------------------------------------------------


@dataclass
class Episode:
    """One labelled interval of the simulated timeline.

    ``params`` (all optional): ``links`` (affected link ids, default all),
    ``zone`` (MOTION region), ``strength``, ``position`` (STILL_PERSON),
    ``hinge`` (DOOR), ``point`` (NEAR_SENSOR_OUTSIDE), ``fraction``
    (PACKET_LOSS), ``speed_mps`` (walkers), ``label`` (ground-truth label).
    """

    t_start_s: float
    t_end_s: float
    kind: str
    params: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.kind not in EPISODE_KINDS:
            raise ValueError(f"unknown episode kind {self.kind!r}")
        if not (0 <= self.t_start_s < self.t_end_s):
            raise ValueError("episode needs 0 <= t_start_s < t_end_s")

    def active(self, t: float) -> bool:
        return self.t_start_s <= t < self.t_end_s


@dataclass
class SyntheticScenario:
    """A simulated session: links, labelled episodes and a seed.

    Optional ``params`` (toy-model knobs, none calibrated to a real room):
    ``environment_seed`` (static multipath and clocks; default ``seed``),
    ``n_reflections`` (6), ``noise_std`` (0.6 int8 counts), ``gain_jitter``
    (0.03), ``timing_jitter_ms`` (1.0), ``target_amplitude`` (20 counts),
    ``carrier_hz``, ``clock_drift_ppm``, ``device_clock_start_us`` and
    ``counter_start`` (to exercise rollover handling).
    """

    name: str
    duration_s: float
    rate_hz: float
    links: list[tuple[str, str]]
    episodes: list[Episode]
    seed: int
    description: str = ""
    node_positions: dict[str, tuple[float, float, float]] = field(default_factory=dict)
    room_size_m: tuple[float, float] = SYNTHETIC_ROOM_SIZE_M
    zones: dict[str, tuple[float, float, float, float]] = field(default_factory=lambda: dict(SYNTHETIC_ZONES))
    params: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not (0 < self.duration_s <= 24 * 3600):
            raise ValueError("duration_s must be in (0, 86400]")
        if not (0 < self.rate_hz <= 1000):
            raise ValueError("rate_hz must be in (0, 1000]")
        if not self.links:
            raise ValueError("a scenario needs at least one link")
        self.links = [(str(t), str(r)) for t, r in self.links]
        if len(set(self.links)) != len(self.links):
            raise ValueError("duplicate link in scenario")
        for ep in self.episodes:
            if ep.t_end_s > self.duration_s + 1e-9:
                raise ValueError(f"episode {ep.kind} ends after the scenario")
            zone = ep.params.get("zone")
            if zone is not None and zone not in self.zones:
                raise ValueError(f"episode {ep.kind} refers to unknown zone {zone!r}")
        positions = dict(self.node_positions)
        txs = sorted({t for t, _ in self.links})
        rxs = sorted({r for _, r in self.links})
        w, d = self.room_size_m
        for i, t in enumerate(txs):
            positions.setdefault(t, (0.0, d * (i + 1) / (len(txs) + 1), BODY_HEIGHT_M))
        for i, r in enumerate(rxs):
            positions.setdefault(r, (w, d * (i + 1) / (len(rxs) + 1), BODY_HEIGHT_M))
        self.node_positions = {k: (float(v[0]), float(v[1]), float(v[2])) for k, v in positions.items()}

    def link_ids(self) -> list[str]:
        return [f"{t}->{r}" for t, r in self.links]

    def affected_links(self, ep: Episode) -> list[str]:
        wanted = ep.params.get("links")
        all_ids = self.link_ids()
        return all_ids if not wanted else [lid for lid in all_ids if lid in set(wanted)]

    def ground_truth(self) -> list[dict[str, Any]]:
        """Labelled intervals, for SOFTWARE TESTS only (simulated truth).

        Gaps not covered by any episode are returned as implicit ``EMPTY``
        intervals. ``motion_expected`` says what a motion detector should
        report if the software works (``None`` = no data expected, i.e.
        SENSOR_OFFLINE / UNKNOWN).
        """
        out: list[dict[str, Any]] = []
        for ep in sorted(self.episodes, key=lambda e: (e.t_start_s, e.t_end_s)):
            out.append(_truth_entry(self, ep, implicit=False))
        covered = sorted((e.t_start_s, e.t_end_s) for e in self.episodes)
        t = 0.0
        gaps: list[tuple[float, float]] = []
        for s, e in covered:
            if s > t + 1e-9:
                gaps.append((t, s))
            t = max(t, e)
        if t < self.duration_s - 1e-9:
            gaps.append((t, self.duration_s))
        for s, e in gaps:
            out.append(_truth_entry(self, Episode(s, e, EMPTY), implicit=True))
        out.sort(key=lambda d: (d["t_start_s"], d["t_end_s"]))
        return out


def _truth_entry(scn: SyntheticScenario, ep: Episode, *, implicit: bool) -> dict[str, Any]:
    label = ep.params.get("label")
    expected: bool | None
    note = ""
    if ep.kind == MOTION:
        label = label or ep.params.get("zone") or MOTION
        expected = True
    elif ep.kind == NEAR_SENSOR_OUTSIDE:
        label = label or "OUTSIDE_TARGET_ROOM"
        expected = True
        note = "Known limitation: motion outside the target room near a sensor also changes the CSI."
    elif ep.kind == STILL_PERSON:
        label = label or STILL_PERSON
        expected = False
        note = "Known limitation: a motionless person is expected to remain undetected."
    elif ep.kind == DOOR:
        label = label or DOOR
        expected = True
        note = "A moving door is motion; it is not a person."
    elif ep.kind == EMPTY:
        label = label or EMPTY
        expected = False
    else:  # DISCONNECT, PACKET_LOSS
        label = label or ep.kind
        expected = None
        note = "No motion label: data is missing or degraded (expect SENSOR_OFFLINE/UNKNOWN or degraded quality)."
    params = {k: v for k, v in ep.params.items() if isinstance(v, (str, int, float, bool, list, tuple))}
    return {
        "t_start_s": float(ep.t_start_s),
        "t_end_s": float(ep.t_end_s),
        "kind": ep.kind,
        "label": label,
        "links": scn.affected_links(ep),
        "motion_expected": expected,
        "implicit": implicit,
        "params": params,
        "note": note,
        "synthetic": True,
    }


# ---------------------------------------------------------------------------
# Builtin scenarios
# ---------------------------------------------------------------------------


def builtin_scenarios() -> dict[str, SyntheticScenario]:
    """Named SIMULATION scenarios (all clearly synthetic)."""
    demo = SyntheticScenario(
        name="demo_walk",
        duration_s=300.0,
        rate_hz=25.0,
        links=[("tx1", "rx1")],
        seed=7,
        node_positions=dict(DEMO_POSITIONS),
        description=(
            "SIMULATED single link. 120 s empty (enough for a 60 s baseline), walking, empty, a person "
            "standing still (expected NOT detected), a door swing, walking again, a 10 s disconnect, empty."
        ),
        episodes=[
            Episode(0, 120, EMPTY),
            Episode(120, 150, MOTION),
            Episode(150, 180, EMPTY),
            Episode(180, 210, STILL_PERSON, {"position": (2.2, 2.3)}),
            Episode(215, 220, DOOR, {"hinge": (1.2, 0.0)}),
            Episode(225, 245, MOTION),
            Episode(250, 260, DISCONNECT),
            Episode(260, 300, EMPTY),
        ],
    )
    quiet = SyntheticScenario(
        name="quiet_only",
        duration_s=180.0,
        rate_hz=25.0,
        links=[("tx1", "rx1")],
        seed=11,
        node_positions=dict(DEMO_POSITIONS),
        description="SIMULATED empty room for 180 s (false-alarm software checks).",
        episodes=[Episode(0, 180, EMPTY)],
    )
    disconnect = SyntheticScenario(
        name="disconnect",
        duration_s=120.0,
        rate_hz=25.0,
        links=[("tx1", "rx1")],
        seed=13,
        node_positions=dict(DEMO_POSITIONS),
        description="SIMULATED empty room, then the receiver disconnects (expect SENSOR_OFFLINE, never 'empty').",
        episodes=[Episode(0, 90, EMPTY), Episode(90, 120, DISCONNECT)],
    )
    zones = SyntheticScenario(
        name="zones_3rx",
        duration_s=270.0,
        rate_hz=25.0,
        links=list(ZONES_3RX_LINKS),
        seed=17,
        node_positions=dict(ZONES_3RX_POSITIONS),
        description=(
            "SIMULATED 4 x 3.5 m room, tx1 with rx1..rx3. 90 s empty (calibration), then walking in zones "
            "A, B, C, then walking outside the room behind rx1."
        ),
        params={"environment_seed": ZONES_ENVIRONMENT_SEED},
        episodes=[
            Episode(0, 90, EMPTY),
            Episode(90, 120, MOTION, {"zone": "A"}),
            Episode(120, 135, EMPTY),
            Episode(135, 165, MOTION, {"zone": "B"}),
            Episode(165, 180, EMPTY),
            Episode(180, 210, MOTION, {"zone": "C"}),
            Episode(210, 225, EMPTY),
            Episode(225, 255, NEAR_SENSOR_OUTSIDE, {"point": OUTSIDE_POINT_3RX}),
            Episode(255, 270, EMPTY),
        ],
    )
    return {s.name: s for s in (demo, quiet, disconnect, zones)}


def zone_session_scenario(
    label: str,
    *,
    seed: int,
    duration_s: float = 60.0,
    links: list[tuple[str, str]] | None = None,
    rate_hz: float = 25.0,
    environment_seed: int = ZONES_ENVIRONMENT_SEED,
) -> SyntheticScenario:
    """A single-label SIMULATED session for zone-estimation SOFTWARE TESTS.

    ``label`` is a zone id from :data:`SYNTHETIC_ZONES`, ``"EMPTY"`` or
    ``"OUTSIDE_TARGET_ROOM"``. All sessions share one simulated environment
    (``environment_seed``) and differ in walker paths and noise (``seed``).
    """
    use_links = list(links) if links is not None else list(ZONES_3RX_LINKS)
    if label in SYNTHETIC_ZONES:
        ep = Episode(0, duration_s, MOTION, {"zone": label, "label": label})
    elif label == "EMPTY":
        ep = Episode(0, duration_s, EMPTY, {"label": "EMPTY"})
    elif label == "OUTSIDE_TARGET_ROOM":
        ep = Episode(0, duration_s, NEAR_SENSOR_OUTSIDE, {"point": OUTSIDE_POINT_3RX, "label": label})
    else:
        raise ValueError(f"unknown zone session label {label!r}; use {sorted(SYNTHETIC_ZONES)}, EMPTY or OUTSIDE_TARGET_ROOM")
    positions = {k: v for k, v in ZONES_3RX_POSITIONS.items()}
    return SyntheticScenario(
        name=f"zone_session_{label}_{seed}",
        duration_s=duration_s,
        rate_hz=rate_hz,
        links=use_links,
        episodes=[ep],
        seed=seed,
        node_positions=positions,
        description=f"SIMULATED single-label session '{label}' for software tests.",
        params={"environment_seed": environment_seed},
    )


# ---------------------------------------------------------------------------
# Toy propagation model
# ---------------------------------------------------------------------------


def _dist_point_segment(p: np.ndarray, a: np.ndarray, b: np.ndarray) -> float:
    ab = b - a
    denom = float(ab @ ab)
    s = 0.0 if denom == 0 else float(np.clip((p - a) @ ab / denom, 0.0, 1.0))
    return float(np.linalg.norm(p - (a + s * ab)))


class _Walker:
    """Piecewise-linear walk through random waypoints inside a rectangle."""

    def __init__(self, rng: np.random.Generator, region: tuple[float, float, float, float], speed: float,
                 duration: float) -> None:
        x0, x1, y0, y1 = region
        margin = 0.2
        if x1 - x0 > 2 * margin:
            x0, x1 = x0 + margin, x1 - margin
        if y1 - y0 > 2 * margin:
            y0, y1 = y0 + margin, y1 - margin
        pts = [np.array([rng.uniform(x0, x1), rng.uniform(y0, y1)])]
        length = 0.0
        needed = speed * duration + 1.0
        # Bounded: at most a few thousand waypoints even for long episodes.
        while length < needed and len(pts) < 5000:
            nxt = np.array([rng.uniform(x0, x1), rng.uniform(y0, y1)])
            step = float(np.linalg.norm(nxt - pts[-1]))
            if step < 0.3:
                continue
            pts.append(nxt)
            length += step
        self.pts = np.asarray(pts)
        seg = np.linalg.norm(np.diff(self.pts, axis=0), axis=1)
        self.cum = np.concatenate([[0.0], np.cumsum(seg)])
        self.speed = speed

    def position(self, t_rel: float) -> np.ndarray:
        s = min(max(t_rel, 0.0) * self.speed, float(self.cum[-1]))
        i = int(np.searchsorted(self.cum, s, side="right")) - 1
        i = min(max(i, 0), len(self.pts) - 2)
        seg_len = self.cum[i + 1] - self.cum[i]
        u = 0.0 if seg_len <= 0 else (s - self.cum[i]) / seg_len
        xy = self.pts[i] + u * (self.pts[i + 1] - self.pts[i])
        return np.array([xy[0], xy[1], BODY_HEIGHT_M])


@dataclass
class _LinkModel:
    index: int
    link_id: str
    tx_id: str
    rx_id: str
    tx: np.ndarray
    rx: np.ndarray
    d_los: float
    a_los: float
    los_delay: float
    refl_amp: np.ndarray  # complex amplitudes of static reflections
    refl_delay: np.ndarray
    gain: float  # model units -> int8 counts
    base_rssi: float
    drift_ppm: float
    dev0_us: int
    counter0: int
    offset_s: float
    h0_power: float = 0.0


def _build_link(scn: SyntheticScenario, idx: int, carrier_hz: float) -> _LinkModel:
    env_seed = int(scn.params.get("environment_seed", scn.seed))
    rng = np.random.default_rng([env_seed, 1, idx])
    tx_id, rx_id = scn.links[idx]
    tx = np.asarray(scn.node_positions[tx_id], dtype=np.float64)
    rx = np.asarray(scn.node_positions[rx_id], dtype=np.float64)
    d_los = max(float(np.linalg.norm(rx - tx)), 0.5)
    # Indoor-like delay spread: reflections 3-18 m longer than the direct
    # path (10-60 ns), which makes the channel frequency-selective across the
    # 20 MHz band as real ESP32 CSI is.
    n_refl = int(scn.params.get("n_reflections", 6))
    extra = rng.uniform(3.0, 18.0, n_refl)
    refl_amp = (
        (1.0 / d_los) * rng.uniform(0.3, 0.9, n_refl) * d_los / (d_los + extra) * 2.0
        * np.exp(1j * rng.uniform(0, 2 * np.pi, n_refl))
    )
    refl_delay = (d_los + extra) / SPEED_OF_LIGHT
    link = _LinkModel(
        index=idx,
        link_id=f"{tx_id}->{rx_id}",
        tx_id=tx_id,
        rx_id=rx_id,
        tx=tx,
        rx=rx,
        d_los=d_los,
        a_los=1.0 / d_los,
        los_delay=d_los / SPEED_OF_LIGHT,
        refl_amp=refl_amp,
        refl_delay=refl_delay,
        gain=1.0,
        base_rssi=-38.0 - 20.0 * math.log10(d_los),
        drift_ppm=float(scn.params.get("clock_drift_ppm", rng.uniform(-25.0, 25.0))),
        dev0_us=int(scn.params.get("device_clock_start_us", int(rng.integers(1_000_000, 1_000_000_000)))),
        counter0=int(scn.params.get("counter_start", 0)) & 0xFFFFFFFF,
        offset_s=idx / (len(scn.links) + 1) / scn.rate_hz,
    )
    f = carrier_hz + _K_VALID * SUBCARRIER_SPACING_HZ
    h0 = _static_response(link, f, los_factor=1.0)
    target = float(scn.params.get("target_amplitude", 20.0))
    link.gain = target / max(float(np.median(np.abs(h0))), 1e-12)
    link.h0_power = float(np.mean(np.abs(h0) ** 2))
    return link


def _paths(amp: np.ndarray, delay: np.ndarray, f: np.ndarray) -> np.ndarray:
    return np.sum(amp[:, None] * np.exp(-2j * np.pi * f[None, :] * delay[:, None]), axis=0)


def _static_response(link: _LinkModel, f: np.ndarray, *, los_factor: float) -> np.ndarray:
    los = link.a_los * los_factor * np.exp(-2j * np.pi * f * link.los_delay)
    return los + _paths(link.refl_amp, link.refl_delay, f)


class _EpisodeState:
    """Per-episode deterministic state shared by all links (one person/door)."""

    def __init__(self, scn: SyntheticScenario, idx: int, ep: Episode) -> None:
        self.ep = ep
        self.links = set(scn.affected_links(ep))
        rng = np.random.default_rng([scn.seed, 1000 + idx])
        self.phase = float(rng.uniform(0, 2 * np.pi))
        self.strength = float(ep.params.get("strength", {DOOR: 2.0, NEAR_SENSOR_OUTSIDE: 1.6}.get(ep.kind, 1.0)))
        self.fraction = float(ep.params.get("fraction", 0.3))
        w, d = scn.room_size_m
        dur = ep.t_end_s - ep.t_start_s
        speed = float(ep.params.get("speed_mps", 0.9))
        self.walker: _Walker | None = None
        self.point: np.ndarray | None = None
        if ep.kind == MOTION:
            zone = ep.params.get("zone")
            region = scn.zones[zone] if zone in scn.zones else (0.0, w, 0.0, d)
            self.walker = _Walker(rng, region, speed, dur)
        elif ep.kind == NEAR_SENSOR_OUTSIDE:
            px, py = ep.params.get("point", (w + 0.8, d / 2))
            self.walker = _Walker(rng, (px - 0.5, px + 0.5, py - 0.5, py + 0.5), speed * 0.7, dur)
        elif ep.kind == STILL_PERSON:
            px, py = ep.params.get("position", (rng.uniform(0.5, w - 0.5), rng.uniform(0.5, d - 0.5)))
            self.point = np.array([float(px), float(py), BODY_HEIGHT_M])
        elif ep.kind == DOOR:
            hx, hy = ep.params.get("hinge", (w / 3, 0.0))
            self.point = np.array([float(hx), float(hy), BODY_HEIGHT_M])

    def scatterer(self, t: float) -> tuple[np.ndarray | None, float]:
        """(scatterer position, extra path length in metres) at time t."""
        t_rel = t - self.ep.t_start_s
        if self.walker is not None:
            return self.walker.position(t_rel), 0.0
        if self.ep.kind == STILL_PERSON and self.point is not None:
            # ~3 mm breathing-like displacement at 0.25 Hz: tiny and slow.
            return self.point, 0.003 * math.sin(2 * math.pi * 0.25 * t_rel)
        if self.ep.kind == DOOR and self.point is not None:
            dur = self.ep.t_end_s - self.ep.t_start_s
            theta = (math.pi / 2) * math.sin(math.pi * min(max(t_rel / dur, 0.0), 1.0))
            leaf = self.point + 0.45 * np.array([math.cos(theta), math.sin(theta), 0.0])
            return leaf, 0.0
        return None, 0.0


def _dynamic_response(link: _LinkModel, states: list[_EpisodeState], t: float, f: np.ndarray) -> tuple[np.ndarray, float]:
    """Sum of episode-driven paths for this link, and the LoS shadowing factor."""
    total = np.zeros(f.shape, dtype=np.complex128)
    los_factor = 1.0
    for st in states:
        kind = st.ep.kind
        if kind not in (MOTION, NEAR_SENSOR_OUTSIDE, STILL_PERSON, DOOR) or link.link_id not in st.links:
            continue
        pos, extra = st.scatterer(t)
        if pos is None:
            continue
        d_seg = _dist_point_segment(pos, link.tx, link.rx)
        sigma = 1.5 if kind == DOOR else 1.2
        amp = link.a_los * SCATTER_COEFF * st.strength * math.exp(-d_seg / sigma)
        path_len = float(np.linalg.norm(pos - link.tx) + np.linalg.norm(link.rx - pos)) + extra
        amps = [amp * np.exp(1j * st.phase)]
        delays = [path_len / SPEED_OF_LIGHT]
        if kind in (MOTION, NEAR_SENSOR_OUTSIDE):
            # Limb/torso micro-motion: a weaker path swinging ~8 cm at ~1.8 Hz.
            swing = 0.08 * math.sin(2 * math.pi * 1.8 * (t - st.ep.t_start_s))
            amps.append(0.35 * amp * np.exp(1j * (st.phase + 1.0)))
            delays.append((path_len + swing) / SPEED_OF_LIGHT)
        if kind != DOOR:
            los_factor *= 1.0 - min(0.6, 0.5 * st.strength) * math.exp(-((d_seg / 0.3) ** 2))
        total += _paths(np.asarray(amps), np.asarray(delays), f)
    return total, max(los_factor, 0.2)


# ---------------------------------------------------------------------------
# Frame generation
# ---------------------------------------------------------------------------


def _link_stream(
    scn: SyntheticScenario,
    link: _LinkModel,
    states: list[_EpisodeState],
    session_id: str,
    start_mono: int,
    start_unix: int,
    time_scale: float,
) -> Iterator[tuple[float, CsiFrame]]:
    carrier = float(scn.params.get("carrier_hz", DEFAULT_CARRIER_HZ))
    noise_std = float(scn.params.get("noise_std", 0.6))
    gain_jitter = float(scn.params.get("gain_jitter", 0.03))
    timing_jitter_s = float(scn.params.get("timing_jitter_ms", 1.0)) / 1000.0
    f = carrier + _K_VALID * SUBCARRIER_SPACING_HZ
    k = _K_VALID
    noise_rng = np.random.default_rng([scn.seed, 2, link.index])
    loss_rng = np.random.default_rng([scn.seed, 3, link.index])
    time_rng = np.random.default_rng([scn.seed, 4, link.index])
    counter_unwrap = CounterUnwrapper(bits=32)
    ts_unwrap = TimestampUnwrapper()
    period = 1.0 / scn.rate_hz
    n_packets = int(math.floor(scn.duration_s * scn.rate_hz))
    identity = DeviceIdentity(
        receiver_id=link.rx_id,
        chip="synthetic",
        firmware_name="roomsense-synthetic-generator",
        firmware_version=SYNTHETIC_MODEL_VERSION,
        identity_source="synthetic",
    )
    static_eps = [st for st in states if st.ep.kind in (DISCONNECT, PACKET_LOSS)]
    guard = period / (2 * (len(scn.links) + 1))

    for n in range(n_packets):
        t_nom = n * period + link.offset_s
        # Consume the random streams for every packet, even dropped ones, so
        # an episode's randomness never depends on what happened earlier.
        air_jitter = float(np.clip(time_rng.normal(0.0, 0.0003), -guard / 4, guard / 4))
        latency = 0.002 + min(abs(float(time_rng.normal(0.0, timing_jitter_s))), guard)
        u_loss = float(loss_rng.random())
        noise = noise_rng.normal(0.0, noise_std, (2, k.size))
        g = 1.0 + float(noise_rng.normal(0.0, gain_jitter))
        common_phase = float(noise_rng.uniform(0.0, 2 * np.pi))
        timing_offset = float(noise_rng.normal(0.0, 25e-9))
        rssi_noise = float(noise_rng.normal(0.0, 0.7))

        t_rf = t_nom + air_jitter
        if t_rf >= scn.duration_s:
            break
        dropped = False
        for st in static_eps:
            if link.link_id in st.links and st.ep.active(t_rf):
                if st.ep.kind == DISCONNECT or u_loss < st.fraction:
                    dropped = True
        if dropped:
            continue

        active = [st for st in states if st.ep.active(t_rf)]
        dyn, los_factor = _dynamic_response(link, active, t_rf, f)
        h = _static_response(link, f, los_factor=los_factor) + dyn
        h = h * link.gain * g * np.exp(1j * (common_phase - 2 * np.pi * k * SUBCARRIER_SPACING_HZ * timing_offset))
        h = h + noise[0] + 1j * noise[1]
        re = np.rint(h.real)
        im = np.rint(h.imag)
        saturated = bool(np.any((re > 127) | (re < -128) | (im > 127) | (im < -128)))
        raw = np.zeros(SYNTHETIC_LAYOUT.total_values, dtype=np.int64)
        raw[2 * _VALID_POS] = np.clip(im, -128, 127).astype(np.int64)  # imaginary first (ESP-IDF order)
        raw[2 * _VALID_POS + 1] = np.clip(re, -128, 127).astype(np.int64)

        power = float(np.mean(np.abs(h / (link.gain * g)) ** 2))
        rssi = int(round(link.base_rssi + 10 * math.log10(max(power, 1e-12) / max(link.h0_power, 1e-12)) + rssi_noise))
        rssi = int(np.clip(rssi, -100, -10))

        flags: list[str] = [QualityFlag.SYNTHETIC.value]
        counter_raw = (link.counter0 + n) & 0xFFFFFFFF
        counter_unw, cflags = counter_unwrap.update(counter_raw)
        flags.extend(cflags)
        dev_raw = (link.dev0_us + int(round(t_rf * 1e6 * (1.0 + link.drift_ppm * 1e-6)))) & 0xFFFFFFFF
        dev_unw, tflags = ts_unwrap.update(dev_raw)
        flags.extend(tflags)
        if saturated:
            flags.append(QualityFlag.SATURATED_VALUES.value)

        t_host = t_rf + latency
        host_off = int(round(t_host * time_scale * 1e9))
        frame = CsiFrame(
            source_mode=SourceMode.SIMULATION,
            session_id=session_id,
            receiver_id=link.rx_id,
            transmitter_id=link.tx_id,
            link_id=link.link_id,
            input_format=InputFormat.SYNTHETIC_V1,
            device=identity,
            frame_counter=counter_raw,
            frame_counter_unwrapped=counter_unw,
            transmitter_counter=None,
            device_timestamp_us=dev_raw,
            device_timestamp_unwrapped_us=dev_unw,
            host_arrival_monotonic_ns=start_mono + host_off,
            host_arrival_unix_ns=start_unix + host_off,
            transmitter_mac=None,
            channel=SYNTHETIC_CHANNEL,
            secondary_channel=0,
            bandwidth_mhz=20,
            sig_mode=None,
            bb_format=None,
            mcs=None,
            rate=None,
            stbc=None,
            rssi_dbm=rssi,
            noise_floor_dbm=None,
            agc_gain=None,
            fft_gain=None,
            sig_len=None,
            rx_state=None,
            antenna=None,
            first_word_invalid=False,
            csi_len=SYNTHETIC_LAYOUT.total_values,
            raw_csi=tuple(raw.tolist()),
            values_are_gain_compensated=False,
            layout_id=SYNTHETIC_LAYOUT.layout_id,
            valid_subcarriers=_VALID_SUBCARRIERS,
            quality_flags=tuple(flags),
        )
        yield t_host, frame


def _link_events(scn: SyntheticScenario, start_mono: int, time_scale: float) -> list[tuple[float, LinkEvent]]:
    events: list[tuple[float, LinkEvent]] = []

    def ev(t: float, link_id: str, kind: str, detail: str) -> tuple[float, LinkEvent]:
        rx = link_id.split("->", 1)[1]
        return t, LinkEvent(
            link_id=link_id,
            receiver_id=rx,
            kind=kind,
            detail=detail,
            host_monotonic_ns=start_mono + int(round(t * time_scale * 1e9)),
            data={"simulated": True},
        )

    for lid in scn.link_ids():
        events.append(ev(0.0, lid, CONNECTED, "simulated link"))
    for ep in scn.episodes:
        if ep.kind != DISCONNECT:
            continue
        for lid in scn.affected_links(ep):
            events.append(ev(ep.t_start_s, lid, DISCONNECTED, "simulated disconnect"))
            if ep.t_end_s < scn.duration_s:
                events.append(ev(ep.t_end_s, lid, CONNECTED, "simulated reconnect"))
    events.sort(key=lambda x: x[0])
    return events


def _timeline(
    scn: SyntheticScenario,
    session_id: str,
    start_mono: int,
    start_unix: int,
    time_scale: float,
    include_events: bool,
) -> Iterator[tuple[float, CsiFrame | LinkEvent]]:
    carrier = float(scn.params.get("carrier_hz", DEFAULT_CARRIER_HZ))
    links = [_build_link(scn, i, carrier) for i in range(len(scn.links))]
    states = [_EpisodeState(scn, i, ep) for i, ep in enumerate(scn.episodes)]
    streams: list[Iterator[tuple[float, Any]]] = [
        _link_stream(scn, lk, states, session_id, start_mono, start_unix, time_scale) for lk in links
    ]
    if include_events:
        streams.append(iter(_link_events(scn, start_mono, time_scale)))
    yield from heapq.merge(*streams, key=lambda item: item[0])


def generate_frames(
    scenario: SyntheticScenario,
    session_id: str,
    *,
    start_unix_ns: int | None = None,
    start_monotonic_ns: int | None = None,
) -> Iterator[CsiFrame]:
    """Offline, deterministic SIMULATED frames in host-arrival order.

    Host timestamps start at fixed arbitrary epochs unless given, so the
    same scenario and seed always produce identical frames.
    """
    mono = SYNTHETIC_EPOCH_MONOTONIC_NS if start_monotonic_ns is None else int(start_monotonic_ns)
    unix = SYNTHETIC_EPOCH_UNIX_NS if start_unix_ns is None else int(start_unix_ns)
    for _, item in _timeline(scenario, session_id, mono, unix, 1.0, include_events=False):
        yield item  # type: ignore[misc]


class SyntheticSource(FrameSource):
    """``SIMULATION`` source. Every frame is flagged ``SYNTHETIC``.

    ``realtime=True`` emits at scenario time divided by ``speed`` and stamps
    host times accordingly. ``realtime=False`` emits as fast as possible
    (for tests); host times then follow the simulated timeline from the start
    instant, not the wall clock.
    """

    mode = SourceMode.SIMULATION

    def __init__(
        self, scenario: SyntheticScenario, *, session_id: str, realtime: bool = True, speed: float = 1.0
    ) -> None:
        if not (0 < speed <= 1000):
            raise ValueError("speed must be in (0, 1000]")
        self.scenario = scenario
        self.session_id = session_id
        self.realtime = realtime
        self.speed = float(speed)
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None
        self._lock = threading.Lock()
        self.frames_emitted = 0
        self.finished = False

    def start(self, sink: Sink) -> None:
        with self._lock:
            if self._thread is not None:
                raise RuntimeError("SyntheticSource can only be started once")
            self._thread = threading.Thread(target=self._run, args=(sink,), name="synthetic", daemon=True)
            self._thread.start()

    def stop(self, timeout_s: float = 5.0) -> None:
        self._stop.set()
        t = self._thread
        if t is not None and t is not threading.current_thread():
            t.join(max(0.0, timeout_s))

    def link_ids(self) -> list[str]:
        return self.scenario.link_ids()

    def describe(self) -> dict[str, Any]:
        s = self.scenario
        return {
            "mode": self.mode.value,
            "session_id": self.session_id,
            "simulated": True,
            "banner": SIMULATED_BANNER,
            "scenario": s.name,
            "description": s.description,
            "duration_s": s.duration_s,
            "rate_hz": s.rate_hz,
            "seed": s.seed,
            "links": s.link_ids(),
            "realtime": self.realtime,
            "speed": self.speed,
            "model": SYNTHETIC_MODEL_VERSION,
            "frames_emitted": self.frames_emitted,
            "finished": self.finished,
        }

    def _run(self, sink: Sink) -> None:
        start_mono = time.monotonic_ns()
        start_unix = time.time_ns()
        scale = (1.0 / self.speed) if self.realtime else 1.0
        try:
            for t, item in _timeline(self.scenario, self.session_id, start_mono, start_unix, scale, True):
                if self._stop.is_set():
                    return
                if self.realtime:
                    remaining = (start_mono + t * scale * 1e9 - time.monotonic_ns()) / 1e9
                    if remaining > 0 and self._stop.wait(remaining):
                        return
                if isinstance(item, CsiFrame):
                    self.frames_emitted += 1
                    self._deliver(sink, FrameEvent(item))
                else:
                    self._deliver(sink, item)
        except Exception as exc:  # never let the thread die silently
            log.exception("synthetic generator failed")
            self._deliver(sink, EndOfStream(f"ERROR: {type(exc).__name__}: {exc}"[:300]))
            return
        if not self._stop.is_set():
            self.finished = True
            self._deliver(sink, EndOfStream("END_OF_SCENARIO"))

    @staticmethod
    def _deliver(sink: Sink, ev: Any) -> None:
        try:
            sink(ev)
        except Exception:
            log.exception("synthetic sink failed")


def with_seed(scenario: SyntheticScenario, seed: int) -> SyntheticScenario:
    """Copy of ``scenario`` with another seed.

    The simulated environment (static multipath, clocks) is kept: only walker
    paths, packet loss and noise change. Pass ``environment_seed`` in
    ``params`` yourself to simulate a different room.
    """
    params = dict(scenario.params)
    params.setdefault("environment_seed", scenario.seed)
    return dataclasses.replace(scenario, seed=int(seed), params=params)
